export const styles = `
:host{display:block;color:var(--primary-text-color);font-family:var(--primary-font-family,Roboto,Arial,sans-serif);font-size:14px;line-height:1.45;--hs-bg:var(--primary-background-color,#f5f7f8);--hs-card:var(--card-background-color,#fff);--hs-border:var(--divider-color,#dce4e9);--hs-muted:var(--secondary-text-color,#546875);--hs-blue:var(--primary-color,#007eab);container-type:inline-size}
*{box-sizing:border-box}button,select{font:inherit;color:inherit}button{cursor:pointer}a{color:var(--hs-blue)}button:focus-visible,a:focus-visible,select:focus-visible,summary:focus-visible{outline:3px solid var(--hs-blue);outline-offset:3px}h1,h2,h3,p{margin:0}h1{font-size:25px;font-weight:500}h2{font-size:18px;font-weight:500}h3{font-size:15px;font-weight:500}strong{font-weight:500}[hidden]{display:none!important}
.shell{background:var(--hs-bg);min-height:100%}.header{background:var(--hs-card);padding:16px 24px 0;border-bottom:1px solid var(--hs-border)}.brand{font-size:19px;font-weight:500;display:flex;align-items:center;gap:10px}.brand ha-icon{color:var(--hs-blue)}.nav{display:flex;gap:24px;margin-top:12px}.nav button{background:none;border:0;border-bottom:3px solid transparent;padding:12px 0;color:var(--hs-muted)}.nav button[aria-current=page]{border-color:var(--hs-blue);color:var(--hs-blue)}
main{padding:24px}.intro{display:flex;justify-content:space-between;gap:16px;margin-bottom:20px;align-items:start}.sub{font-size:13px;color:var(--hs-muted);margin-top:5px}.small{font-size:12px;color:var(--hs-muted)}.grid{display:grid;grid-template-columns:minmax(0,1.65fr) minmax(220px,1fr);gap:18px;align-items:start}.stack{display:grid;gap:18px;min-width:0}
.panel{background:var(--hs-card);border:1px solid var(--hs-border);border-radius:var(--ha-card-border-radius,12px);overflow:hidden}.panel-head{padding:17px 18px 12px;display:flex;justify-content:space-between;align-items:center;gap:10px}.body{padding:0 18px 18px}.row{width:100%;text-align:left;display:flex;align-items:center;gap:12px;padding:14px 18px;border:0;border-top:1px solid var(--hs-border);background:transparent}.row:hover{background:var(--secondary-background-color)}.row-main{flex:1;min-width:0;overflow-wrap:anywhere}.row small{display:block;font-size:12px;color:var(--hs-muted);margin-top:3px}.tag{padding:4px 8px;font-size:12px;border-radius:5px;background:var(--secondary-background-color);color:var(--hs-muted);white-space:nowrap}.tag.ready,.tag.pass{color:var(--success-color,#207645)}.tag.blocked,.tag.fail{color:var(--error-color,#b3261e)}.tag.unknown,.tag.warn,.tag.degraded{color:var(--warning-color,#976500)}
.issue{border-left:4px solid var(--error-color,#b3261e);background:var(--hs-card);padding:18px;margin:0 0 14px;border-radius:8px}.issue.situation{border-color:var(--warning-color,#976500)}.issue p{margin-top:5px}.issue h2{font-size:19px}.actions{display:flex;gap:12px;flex-wrap:wrap;margin-top:12px}.button{display:inline-flex;align-items:center;justify-content:center;gap:6px;border:1px solid var(--hs-border);background:var(--hs-card);padding:8px 12px;min-height:40px;border-radius:6px;text-decoration:none}.primary{background:var(--hs-blue);color:var(--text-primary-color,#fff);border-color:var(--hs-blue)}.link{background:none;border:0;padding:8px 0;color:var(--hs-blue);text-align:left;min-height:36px}.empty{padding:18px;background:var(--hs-card);border:1px solid var(--hs-border);border-radius:10px;margin-bottom:18px}.note{padding:12px;background:var(--secondary-background-color);border-radius:6px;margin-top:12px;font-size:13px}.stat{display:flex;justify-content:space-between;gap:14px;padding:9px 0;border-bottom:1px solid var(--hs-border)}.stat:last-child{border:0}.stat strong{font-variant-numeric:tabular-nums}
.table-wrap{overflow:auto}table{width:100%;border-collapse:collapse;font-size:13px}th,td{text-align:left;vertical-align:top;padding:12px 14px;border-bottom:1px solid var(--hs-border)}th{font-weight:500;color:var(--hs-muted);background:var(--hs-bg)}td small{display:block;color:var(--hs-muted);margin-top:3px}.mono{font:12px ui-monospace,monospace;overflow-wrap:anywhere}.house{display:grid;grid-template-columns:220px minmax(0,1fr);gap:18px}.locations{padding:8px}.location{display:block;width:100%;text-align:left;border:0;background:none;padding:10px;border-radius:5px}.location[aria-pressed=true]{color:var(--hs-blue);background:var(--secondary-background-color)}.location-group{font-size:12px;padding:10px;color:var(--hs-muted)}.banner{padding:18px;border:1px solid var(--hs-border);border-left:4px solid var(--warning-color,#976500);border-radius:8px;background:var(--hs-card)}.banner p{margin-top:7px}
dialog{margin:auto;background:var(--hs-card);color:var(--primary-text-color);border:1px solid var(--hs-border);padding:0;border-radius:12px;width:min(660px,calc(100% - 24px));max-height:90vh}dialog::backdrop{background:#0007}.dialog-head{padding:18px;border-bottom:1px solid var(--hs-border);display:flex;justify-content:space-between;gap:16px;align-items:start}.dialog-body{padding:18px;display:grid;gap:20px;overflow-wrap:anywhere}.dialog-head>div{min-width:0;overflow-wrap:anywhere}.detail h3{margin-bottom:8px}.detail p+p{margin-top:8px}.detail ul{padding-left:18px}.detail li{margin:7px 0}details{border-top:1px solid var(--hs-border);padding-top:12px}summary{color:var(--hs-blue);cursor:pointer}pre{white-space:pre-wrap;overflow-wrap:anywhere;font:12px ui-monospace,monospace;max-height:300px;overflow:auto}select{background:var(--hs-card);border:1px solid var(--hs-border);border-radius:6px;padding:9px;max-width:100%}
@container(max-width:720px){main{padding:18px 14px}.header{padding-left:14px;padding-right:14px}.grid,.house{grid-template-columns:1fr}.locations{display:flex;flex-wrap:wrap;gap:4px}.location-group{width:100%}.location{width:auto}.intro{flex-wrap:wrap}}
@container(max-width:430px){.row{padding:13px 12px;gap:8px}.row ha-icon{display:none}.nav{gap:18px}.issue{padding:14px}h1{font-size:23px}.body{padding-left:12px;padding-right:12px}.panel-head{padding-left:12px;padding-right:12px}}
`;
