"""Require the documented coverage floor for both statements and branches."""

import json
from pathlib import Path


def main() -> None:
    """Check the coverage JSON generated by the preceding pytest run."""
    totals = json.loads(Path("coverage.json").read_text())["totals"]
    for label, covered, total in (
        ("statement", totals["covered_lines"], totals["num_statements"]),
        ("branch", totals["covered_branches"], totals["num_branches"]),
    ):
        if total == 0 or covered / total < 0.95:
            raise SystemExit(f"{label} coverage is below 95 percent: {covered}/{total}")


if __name__ == "__main__":
    main()
